// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/customer-orders/CustomerOrdersPreview.tsx": () => import("../components/mockups/customer-orders/CustomerOrdersPreview.tsx"),
  "./components/mockups/admin-requests/AdminGeneralRequestsPreview.tsx": () => import("../components/mockups/admin-requests/AdminGeneralRequestsPreview.tsx")
};
